import { neon } from "@neondatabase/serverless";
import { readFileSync } from "fs";
import { resolve } from "path";

const envContent = readFileSync(resolve(process.cwd(), ".env.local"), "utf-8");
for (const line of envContent.split("\n")) {
  const match = line.match(/^([^#=]+)=(.*)$/);
  if (match) process.env[match[1].trim()] = match[2].trim();
}

const projects = [
  {
    slug: "coach-mohamed-roshdy",
    image: "/uploads/coach-shiko-proj.jpg",
    tag: "Website Development",
    title: "Coach Mohamed Roshdy",
    desc: "A bilingual fitness coaching platform with personalized training programs, nutrition plans, and client transformation showcases.",
    fullDesc: "Coach Mohamed Roshdy needed a professional online presence that could handle bilingual content (English/Arabic), showcase client transformations, and convert visitors into coaching clients. We built a high-performance Next.js application with a dark, motivational design that matches the intensity of his brand. The site features five tiered coaching packages with multi-currency pricing (USD/EGP), a transformation gallery with before/after imagery, and seamless WhatsApp integration for direct client communication. Every element was designed to build trust and drive conversions.",
    client: "Mohamed Roshdy",
    industry: "Fitness & Coaching",
    timeline: "4 weeks",
    url: "https://coachmohamedroshdy.com",
    services: ["Website Development", "UI/UX Design", "Bilingual Support"],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Vercel"],
    challenge: "The client needed a platform that could serve both English and Arabic-speaking audiences with a seamless language toggle, while maintaining a high-energy, motivational brand feel. The site also needed to clearly present five different coaching tiers with transparent pricing in multiple currencies.",
    solution: "We built a fully bilingual Next.js application with RTL support for Arabic content. The design uses dark backgrounds with high-contrast typography to create an intense, gym-inspired atmosphere. Each coaching plan is presented in a clear comparison format with pricing in both USD and EGP. The transformation gallery uses optimized image loading with blob storage for fast performance.",
    results: [
      { label: "Page Load Time", value: "<2s" },
      { label: "Languages", value: "2 (EN/AR)" },
      { label: "Coaching Plans", value: "5 Tiers" },
      { label: "Mobile Score", value: "96/100" },
    ],
    features: [
      "Bilingual support with English/Arabic toggle and full RTL layout",
      "5 tiered coaching packages ($75-$500/mo) with multi-currency pricing",
      "Client transformation gallery with before/after showcases",
      "WhatsApp integration for direct coach communication",
      "Mobile-first responsive design optimized for all devices",
      "SEO-optimized with structured data for local search visibility",
    ],
    testimonial: {
      quote: "The website perfectly captures the energy of my coaching brand. My clients love how easy it is to browse plans and see real transformation results.",
      author: "Mohamed Roshdy",
      role: "Founder & Head Coach",
    },
    gallery: [
      { image: "", caption: "Hero section with motivational messaging and clear CTAs" },
      { image: "", caption: "Five-tier coaching plans with transparent pricing" },
      { image: "", caption: "Client transformation gallery showcasing real results" },
      { image: "", caption: "Bilingual interface with seamless English/Arabic toggle" },
    ],
  },
  {
    slug: "initio",
    image: "/uploads/initio-proj.png",
    tag: "Website Development",
    title: "Initio",
    desc: "A premium digital experience for Saudi Arabia's leading event and production company, serving clients like Saudi Aramco and Riyadh Season.",
    fullDesc: "Initio needed a website that matched the caliber of their clients: Saudi Aramco, SABIC, Sadara, and Riyadh Season. We built a high-end Next.js application with cinematic video backgrounds, custom cursor interactions, and smooth scroll animations that reflect the precision and luxury of their event production work. The site communicates their integrated model across event management, technology, branding, and digital production in a way that feels as polished as the events they produce.",
    client: "Initio",
    industry: "Events & Production",
    timeline: "6 weeks",
    url: "https://www.initio.sa",
    services: ["Website Development", "UI/UX Design", "Motion & Animation"],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Vercel", "Framer Motion"],
    challenge: "Initio operates at the highest level of event production in Saudi Arabia, working with government entities and Fortune 500 companies. Their previous online presence did not reflect the quality of their work. They needed a website that communicates luxury, precision, and capability without being flashy or overdesigned.",
    solution: "We designed a dark, cinematic interface with a video hero section, custom cursor system, and smooth scroll animations. The typography pairs EB Garamond (luxury serif) with Montserrat (modern sans) to balance elegance with professionalism. Each service is presented with rich imagery from real events, and the four-step process section builds trust through transparency. The site loads fast despite heavy media thanks to optimized video preloading and Next.js image optimization.",
    results: [
      { label: "Page Load", value: "<3s" },
      { label: "Client Tier", value: "Enterprise" },
      { label: "Services Shown", value: "4 Core" },
      { label: "Languages", value: "2 (EN/AR)" },
    ],
    features: [
      "Cinematic video hero with preloaded media for instant playback",
      "Custom cursor system that enhances the premium browsing experience",
      "Smooth scroll animations with parallax effects throughout",
      "Four-pillar service showcase: Events, Technology, Branding, Digital Production",
      "Client roster featuring Saudi Aramco, SABIC, Sadara, and Riyadh Season",
      "Bilingual support with English and Arabic content",
      "WhatsApp integration for instant client communication",
      "Mobile-optimized with performance-first architecture",
    ],
    testimonial: {
      quote: "VELIQ understood our brand from day one. The website captures exactly who we are: precise, premium, and focused on delivering unforgettable experiences.",
      author: "Initio Team",
      role: "Initio, Saudi Arabia",
    },
    gallery: [
      { image: "", caption: "Cinematic video hero with smooth scroll interactions" },
      { image: "", caption: "Service showcase with real event photography" },
      { image: "", caption: "Client roster featuring top Saudi organizations" },
      { image: "", caption: "Four-step process methodology" },
    ],
  },
  {
    slug: "saudi-hayat",
    image: "/uploads/saudi-hayat-proj.png",
    tag: "Website Development",
    title: "Saudi Hayat",
    desc: "A bilingual corporate website for one of Saudi Arabia's leading real estate developers, aligned with Vision 2030.",
    fullDesc: "Saudi Hayat needed a digital presence that reflects 11+ years of experience building inspiring urban environments across the Kingdom. We designed and developed a bilingual (Arabic/English) corporate website with full RTL support, showcasing their portfolio of residential and commercial developments, four core service lines, and their commitment to sustainable urban living. The site positions Hayat as a trusted partner in Saudi Arabia's Vision 2030 transformation.",
    client: "Saudi Hayat",
    industry: "Real Estate & Development",
    timeline: "5 weeks",
    url: "https://www.saudihayat.com",
    services: ["Website Development", "UI/UX Design", "Bilingual Support"],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Vercel"],
    challenge: "Hayat needed a website that could serve both Arabic and English-speaking audiences with seamless RTL/LTR switching, while presenting complex real estate projects and corporate credentials in a way that builds trust with high-net-worth investors and family buyers in the Saudi market.",
    solution: "We built a fully bilingual Next.js application with native RTL support for Arabic content. The design uses a clean, professional aesthetic with dark mode capability, high-quality project photography, and prominent display of their ISO 45001:2018 certification. Each service line (development, management, marketing, consulting) has dedicated sections with clear value propositions. Key company stats are presented with animated counters to build credibility on first impression.",
    results: [
      { label: "Languages", value: "2 (AR/EN)" },
      { label: "Experience", value: "11+ Years" },
      { label: "Services", value: "4 Core" },
      { label: "ISO Certified", value: "45001" },
    ],
    features: [
      "Full bilingual support with native Arabic RTL layout and English LTR",
      "Project portfolio showcase with high-quality imagery of completed developments",
      "Four service pillars: Development, Management, Marketing, Consulting",
      "Animated statistics displaying years of experience, projects, and team size",
      "ISO 45001:2018 certification badge for trust and credibility",
      "Dark mode toggle for enhanced browsing experience",
      "Careers section for talent acquisition aligned with Saudi talent development",
      "Mobile-first responsive design optimized for all devices",
    ],
    testimonial: {
      quote: "The website perfectly represents our vision of building inspiring urban environments for generations. The bilingual experience is seamless and our clients love navigating our project portfolio.",
      author: "Hayat Team",
      role: "Saudi Hayat",
    },
    gallery: [
      { image: "", caption: "Homepage hero with company tagline and Vision 2030 alignment" },
      { image: "", caption: "Project portfolio showcasing Hayat Tower and residential developments" },
      { image: "", caption: "Four-pillar service showcase with dedicated sections" },
      { image: "", caption: "Company statistics with animated counters" },
    ],
  },
  {
    slug: "alfa-transport",
    image: "/uploads/alfa-transport-proj.png",
    tag: "Website Development",
    title: "ALFA Transport",
    desc: "A bilingual corporate website for a leading Saudi logistics company with 17 years of experience, serving clients like SABIC and Qassim Cement.",
    fullDesc: "ALFA Transport is a specialized logistics company operating across Saudi Arabia and the Gulf region since 2007. They needed a website that communicates their 17-year track record, four specialized service lines, and partnerships with major industrial clients like SABIC. We built a bilingual Next.js application with a professional design that balances their heritage with modern technology capabilities, featuring real-time shipment tracking, safety compliance messaging, and direct WhatsApp integration for instant client communication.",
    client: "ALFA Transport",
    industry: "Logistics & Transportation",
    timeline: "5 weeks",
    url: "https://www.alfatransport.sa",
    services: ["Website Development", "UI/UX Design", "Bilingual Support"],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Vercel"],
    challenge: "ALFA needed a digital presence that positions them as a modern logistics leader while honoring 17 years of operational excellence. The site had to serve Arabic and English audiences, present four complex service lines clearly, and build trust with enterprise clients like SABIC and Tawuniya through credibility signals and social proof.",
    solution: "We designed a bold, contemporary interface using ALFA's brand colors (navy blue, burgundy, gold) with gradient overlays and floating geometric elements. The four service pillars are each presented with dedicated sections and direct WhatsApp CTAs for instant inquiries. Client testimonials from major Saudi corporations are prominently featured. The bilingual architecture supports seamless Arabic RTL and English LTR switching. Animated statistics highlight fleet size, partnerships, and safe shipment records.",
    results: [
      { label: "Experience", value: "17 Years" },
      { label: "Fleet Size", value: "50+" },
      { label: "Languages", value: "2 (AR/EN)" },
      { label: "Key Partners", value: "SABIC" },
    ],
    features: [
      "Bilingual support with native Arabic RTL and English LTR layouts",
      "Four specialized service showcases: Land Transport, Cement Distribution, Cargo Inspection, International Solutions",
      "Client testimonials featuring SABIC, Tawuniya, and Qassim Cement",
      "Animated statistics displaying fleet size, partnerships, and safe shipments",
      "Direct WhatsApp integration on every service for instant communication",
      "Brand-aligned design with navy, burgundy, and gold color palette",
      "Careers section for talent acquisition across Saudi regions",
      "Mobile-first responsive design with performance optimization",
    ],
    testimonial: {
      quote: "VELIQ delivered a website that truly represents ALFA's position as a logistics leader. The bilingual experience and professional design have strengthened our credibility with enterprise clients.",
      author: "ALFA Team",
      role: "ALFA Transport, Saudi Arabia",
    },
    gallery: [
      { image: "", caption: "Hero section with bold tagline: Smart Transport, Complete Safety" },
      { image: "", caption: "Four service pillars with dedicated WhatsApp CTAs" },
      { image: "", caption: "Client testimonials from SABIC and major Saudi corporations" },
      { image: "", caption: "Animated statistics showcasing 17 years of operations" },
    ],
  },
  {
    slug: "coach-batool",
    hidden: true,
    image: "/uploads/coach-batool-proj.png",
    tag: "Website Development",
    title: "Coach Batoula",
    desc: "A bilingual nutrition coaching platform for Arab women, featuring subscription plans, digital products, and 500+ success stories.",
    fullDesc: "Coach Batoula is a certified nutrition and life coach with a unique philosophy: eat from your home kitchen with your family and still stay healthy. She needed a platform that could sell coaching subscriptions, digital recipe books, and one-time consultations while showcasing 500+ client success stories. We built a bilingual Next.js application with a warm, welcoming design that resonates with her primarily Arabic-speaking female audience, complete with WhatsApp-first communication and a mobile app promotion section.",
    client: "Coach Batoula",
    industry: "Nutrition & Coaching",
    timeline: "4 weeks",
    url: "https://www.coachbatool.com",
    services: ["Website Development", "UI/UX Design", "Bilingual Support"],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Vercel"],
    challenge: "Batoula needed a website that could convert Arabic-speaking women into coaching clients while presenting multiple pricing tiers, digital products, and hundreds of success stories in a way that feels personal and trustworthy. The site also needed to support both Arabic RTL and English LTR seamlessly.",
    solution: "We designed a warm, feminine interface with Cairo font for Arabic readability and clean typography for English. Three subscription tiers ($45/mo, $99/3mo, $299/yr) plus a $15 one-time consultation are presented in a clear comparison format. Digital products (recipe books at $5-$10) have their own showcase section. The 500+ success stories and 3,500+ kg of client fat loss are highlighted with animated counters. WhatsApp integration enables direct coaching communication, matching Batoula's personal approach.",
    results: [
      { label: "Success Stories", value: "500+" },
      { label: "Fat Lost (kg)", value: "3,500+" },
      { label: "Training Hours", value: "2,000+" },
      { label: "Languages", value: "2 (AR/EN)" },
    ],
    features: [
      "Three subscription tiers with clear pricing: $45/mo, $99/3mo, $299/year",
      "One-time consultation booking at $15 for 40-minute personalized sessions",
      "Digital products marketplace: recipe books and nutrition guides",
      "500+ client success stories with before/after transformations",
      "Bilingual support with native Arabic RTL and English LTR layouts",
      "WhatsApp-first communication model for personal coaching",
      "Mobile app promotion section driving downloads",
      "Certification and credential showcase building professional trust",
    ],
    testimonial: {
      quote: "The website captures my philosophy perfectly: eat from your home kitchen, stay healthy. My clients find it easy to choose their plan and start their journey immediately.",
      author: "Coach Batoula",
      role: "Certified Nutrition & Life Coach",
    },
    gallery: [
      { image: "", caption: "Hero section with warm design and coaching philosophy" },
      { image: "", caption: "Three-tier subscription plans with transparent pricing" },
      { image: "", caption: "Success stories showcasing 500+ client transformations" },
      { image: "", caption: "Digital products marketplace with recipe books" },
    ],
  },
  {
    slug: "fanous-clinic",
    image: "/uploads/fanous-clinic-proj.png",
    tag: "Website Development",
    title: "Fanous Clinic",
    desc: "A modern healthcare website for a Charlotte-based primary care clinic with an innovative collaborative care model.",
    fullDesc: "Fanous Clinic is a primary care practice in Charlotte, North Carolina, with a unique 'Huddle' model where physicians and clinical pharmacists collaborate in a single visit. We built a professional, trust-driven website that communicates their five service lines, showcases insurance partnerships, and makes appointment booking seamless. The design balances clinical credibility with warmth, reflecting their faith-based mission of compassionate, illuminated healthcare.",
    client: "Fanous Clinic",
    industry: "Healthcare",
    timeline: "5 weeks",
    url: "https://www.fanousclinic.com",
    services: ["Website Development", "UI/UX Design", "SEO"],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Vercel"],
    challenge: "Fanous Clinic needed a website that differentiates them in a competitive healthcare market by clearly communicating their unique 'Huddle' model (two experts in one visit), while building trust through insurance partner logos, patient testimonials, and professional facility imagery. The site also needed strong SEO for local Charlotte search visibility.",
    solution: "We designed a clean, teal-accented interface that feels both professional and approachable. Five service cards present each offering clearly with dedicated detail pages. A prominent insurance partnership bar displays 7 accepted providers. Patient testimonials are shown in a carousel with 5-star ratings. The facility gallery showcases the modern clinic environment. SEO was built in from day one with structured data, local schema markup, and optimized meta tags for Charlotte-area healthcare searches.",
    results: [
      { label: "Physician Exp.", value: "20+ Years" },
      { label: "Insurance Partners", value: "7" },
      { label: "Services", value: "5 Core" },
      { label: "Patient Rating", value: "5 Stars" },
    ],
    features: [
      "Five service showcases: Primary Care, Medication Optimization, Chronic Disease, Wellness Coaching, Early Bird Care",
      "Insurance partnership bar displaying 7 accepted providers (Aetna, BCBS, Cigna, etc.)",
      "Patient testimonial carousel with 5-star reviews",
      "Professional facility photo gallery showcasing the clinic environment",
      "Online appointment booking with telehealth option",
      "Blog section for patient education and health content",
      "Team member profiles highlighting credentials and experience",
      "Local SEO optimization for Charlotte, NC healthcare searches",
    ],
    testimonial: {
      quote: "VELIQ created a website that truly reflects our mission. Patients tell us the site feels warm and professional, exactly the experience we deliver in person.",
      author: "Fanous Clinic Team",
      role: "Fanous Clinic, Charlotte NC",
    },
    gallery: [
      { image: "", caption: "Hero section with appointment booking CTA" },
      { image: "", caption: "Five-service showcase with detailed descriptions" },
      { image: "", caption: "Insurance partnership bar and patient testimonials" },
      { image: "", caption: "Professional facility gallery" },
    ],
  },
  {
    slug: "crewhub-studio",
    image: "/uploads/crewhub-studio-proj.png",
    tag: "Website Development",
    title: "CrewHub Studio",
    desc: "A dark, cinematic portfolio website for a Gulf-based creative agency specializing in exhibitions, events, and branding.",
    fullDesc: "CrewHub Studio is a creative agency operating across the Gulf region, delivering exhibition design, event production, and branding for corporate clients. We built a bold portfolio website with a dark theme, purple accents, and interactive project galleries that showcase their work with immersive modal views. The site features an animated scrolling ticker, smooth hover effects, and a responsive layout that positions CrewHub as a premium creative partner.",
    client: "CrewHub Studio",
    industry: "Creative Agency",
    timeline: "4 weeks",
    url: "https://crewhubstudio.com",
    services: ["Website Development", "UI/UX Design"],
    technologies: ["WordPress", "JavaScript", "CSS3", "EmailJS"],
    challenge: "CrewHub needed a portfolio website that could showcase exhibition builds, events, and branding projects with rich imagery while maintaining fast load times. The site had to feel as creative as the work they produce, standing out from template-based agency sites in the Gulf market.",
    solution: "We designed a dark, cinematic interface with purple accent colors and smooth animations. Each project opens in an interactive modal gallery with 13-20 images per project. An animated ticker reinforces their tagline. The three service pillars are presented with hover-activated cards. EmailJS powers the contact form for direct inquiries without backend complexity.",
    results: [
      { label: "Projects Shown", value: "5+" },
      { label: "Gallery Images", value: "60+" },
      { label: "Services", value: "3 Core" },
      { label: "Load Time", value: "<3s" },
    ],
    features: [
      "Interactive modal project galleries with 13-20 images per project",
      "Dark cinematic design with purple accent color palette",
      "Animated scrolling ticker with brand tagline",
      "Three service showcases: Exhibition Design, Event Design, Branding",
      "Hover-activated service cards with smooth transitions",
      "EmailJS contact form integration for direct inquiries",
      "Mobile-responsive design across all devices",
      "Social media integration: Twitter, Instagram, LinkedIn, Pinterest",
    ],
    testimonial: {
      quote: "The website captures the energy and creativity of our studio. Clients are impressed by the portfolio galleries before we even meet them.",
      author: "CrewHub Team",
      role: "CrewHub Studio",
    },
    gallery: [],
  },
  {
    slug: "redbone-gym",
    hidden: true,
    image: "/uploads/redbone-gym-proj.png",
    tag: "Website Development",
    title: "RedBone Gym",
    desc: "A bold fitness website for a premium Cairo gym with membership plans, professional services, and mobile app integration.",
    fullDesc: "RedBone Gym is a premium fitness facility in Nasr City, Cairo, owned by Captain Maged. We built a high-energy website with a dark theme and red accents that matches the intensity of the gym experience. The site features four membership tiers, professional consultation bookings, wellness services, and promotion of their native iOS and Android apps. Every element is designed to convert visitors into members.",
    client: "RedBone Gym",
    industry: "Fitness & Wellness",
    timeline: "4 weeks",
    url: "https://www.redbonegym.com",
    services: ["Website Development", "UI/UX Design"],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Vercel"],
    challenge: "RedBone needed a website that communicates their premium positioning in Cairo's competitive gym market, clearly presents multiple membership tiers and professional services with pricing, and drives mobile app downloads for member engagement.",
    solution: "We designed a dark, high-energy interface with red accent colors (#CC2421) that matches the gym's brand identity. Four membership plans (700-3,900 EGP) are presented in a clear comparison format. Professional services including consultations, cupping therapy, and InBody analysis each have dedicated sections with pricing. The mobile app is prominently promoted with download links for iOS and Android.",
    results: [
      { label: "Membership Tiers", value: "4" },
      { label: "Operating Hours", value: "18hrs/day" },
      { label: "Mobile Apps", value: "iOS & Android" },
      { label: "Services", value: "5+" },
    ],
    features: [
      "Four membership tiers with transparent pricing (700-3,900 EGP)",
      "Professional consultation bookings with Dr. Mostafa and Dr. Mohsen",
      "Wellness services: cupping, massage therapy, InBody analysis",
      "Native iOS and Android mobile app promotion",
      "Interactive facility gallery with hover animations",
      "Dark theme with red accent colors matching brand identity",
      "Operating hours display (8 AM - 2 AM daily)",
      "Science-based program messaging differentiating from typical gyms",
    ],
    testimonial: {
      quote: "The website brings the RedBone experience online. Members tell us it's the best gym website they've seen in Cairo.",
      author: "Captain Maged",
      role: "Founder, RedBone Gym",
    },
    gallery: [],
  },
  {
    slug: "yamin-estate",
    hidden: true,
    image: "/uploads/yamin-estate-proj.png",
    tag: "Website Development",
    title: "Yamin Estate",
    desc: "A luxury bilingual real estate platform for a Saudi developer targeting 1,000 residential units by 2030.",
    fullDesc: "Yamin Estate is a premium Saudi real estate developer building sustainable residential and commercial communities. We created a luxury bilingual website with warm, earthy aesthetics that reflect their commitment to quality living. The site showcases their active developments, six service lines, and ambitious Vision 2030-aligned roadmap of 1,000 residential units. The design uses Poppins typography, smooth gradient transitions, and high-quality imagery to communicate trust and sophistication.",
    client: "Yamin Estate",
    industry: "Real Estate & Development",
    timeline: "5 weeks",
    url: "https://www.yamin.estate",
    services: ["Website Development", "UI/UX Design", "Bilingual Support"],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Vercel"],
    challenge: "Yamin needed a website that positions them as a luxury developer while communicating their sustainability values and Vision 2030 alignment. The site had to showcase active projects with rich imagery and serve both Arabic and English-speaking investors and home buyers.",
    solution: "We designed a warm, sophisticated interface with taupe and brown tones that evoke luxury and earthiness. Each active development has a dedicated showcase with smart home features, location maps, and pricing. The six service pillars are presented clearly. Animated counters highlight their 25+ team members, 16+ partnerships, and 1,000-unit target. Full bilingual support with RTL Arabic and LTR English.",
    results: [
      { label: "Target Units", value: "1,000" },
      { label: "Team Size", value: "25+" },
      { label: "Partnerships", value: "16+" },
      { label: "Languages", value: "2 (AR/EN)" },
    ],
    features: [
      "Luxury design with warm taupe and brown color palette",
      "Active project showcases with smart home feature highlights",
      "Six service pillars: Development, Commercial, Tourism, Management, Advisory, Marketing",
      "Animated statistics counters for team, partnerships, and targets",
      "Bilingual support with native Arabic RTL and English LTR",
      "Sustainability messaging aligned with Saudi Vision 2030",
      "Core values section: Credibility, Sustainability, Innovation, Quality",
      "Mobile-responsive with performance-first architecture",
    ],
    testimonial: {
      quote: "VELIQ delivered a website that truly reflects our vision of building sustainable communities. The luxury feel matches the quality of our developments.",
      author: "Yamin Team",
      role: "Yamin Estate, Saudi Arabia",
    },
    gallery: [],
  },
  {
    slug: "captain-maged",
    hidden: true,
    image: "/uploads/captain-maged-proj.png",
    tag: "Website Support",
    title: "Captain Maged",
    desc: "Ongoing website support and maintenance for a fitness education platform focused on anatomy and nutrition guidance.",
    fullDesc: "Captain Maged runs a health and fitness education platform covering anatomy and nutrition science. We provide ongoing website support including performance optimization, security updates, content management, and technical maintenance. Our team ensures the WordPress-based site stays fast, secure, and up-to-date so Captain Maged can focus on creating educational content for his growing audience.",
    client: "Captain Maged",
    industry: "Fitness & Education",
    timeline: "Ongoing",
    url: "https://captainmagedcm.com",
    services: ["Website Support", "Performance Optimization", "Security"],
    technologies: ["WordPress", "Elementor", "WooCommerce", "Astra Theme"],
    challenge: "Captain Maged's WordPress site needed ongoing attention to maintain performance, security, and compatibility as plugins and themes update. Content updates and page modifications needed to happen quickly without disrupting the user experience.",
    solution: "We provide monthly maintenance cycles including plugin/theme updates, security scanning, performance optimization, and content updates. Backup systems ensure disaster recovery readiness. Regular speed audits keep the site loading fast. We handle all technical changes so the client can focus on content creation.",
    results: [
      { label: "Uptime", value: "99.9%" },
      { label: "Support Type", value: "Ongoing" },
      { label: "Response Time", value: "<12h" },
      { label: "Updates/Month", value: "4+" },
    ],
    features: [
      "Monthly plugin, theme, and WordPress core updates",
      "Security scanning and vulnerability patching",
      "Performance optimization with regular speed audits",
      "Content updates and page modifications on demand",
      "Database backups and disaster recovery planning",
      "Cross-browser and device compatibility testing",
      "Uptime monitoring with incident response",
      "Priority support with dedicated account manager",
    ],
    testimonial: {
      quote: "Having VELIQ handle the technical side means I can focus on creating content. The site runs smoothly and I never worry about downtime.",
      author: "Captain Maged",
      role: "Fitness Educator",
    },
    gallery: [],
  },
  {
    slug: "window-adv",
    hidden: true,
    image: "/uploads/window-adv-proj.png",
    tag: "Search Engine Optimization",
    title: "Window Advertising",
    desc: "SEO strategy and optimization for a Riyadh-based advertising agency with 25+ years of experience and 1,000+ clients.",
    fullDesc: "Window Advertising is a full-service advertising agency in Riyadh with over 25 years of experience serving government and corporate clients. We implemented a comprehensive SEO strategy to increase their organic visibility in the competitive Saudi advertising market, targeting high-intent keywords for exhibition design, commercial printing, and 3D model manufacturing services across Riyadh and the broader Saudi market.",
    client: "Window Advertising",
    industry: "Advertising Agency",
    timeline: "Ongoing",
    url: "https://windowadv.com",
    services: ["Search Engine Optimization", "Technical SEO", "Content Strategy"],
    technologies: ["Google Search Console", "Google Analytics", "Ahrefs", "Screaming Frog"],
    challenge: "Despite 25+ years in the market and 1,000+ clients, Window Advertising had limited organic search visibility. Their services (exhibition design, printing, 3D manufacturing) were not ranking for relevant Arabic and English search queries in the Riyadh market.",
    solution: "We conducted a full technical SEO audit, fixed crawlability issues, implemented Arabic-optimized schema markup, and built a keyword strategy targeting both Arabic and English search terms. On-page optimization covered all service pages with proper meta tags, headings, and internal linking. Local SEO was prioritized with Google Business Profile optimization for Riyadh-area searches.",
    results: [
      { label: "Experience", value: "25+ Years" },
      { label: "Client Base", value: "1,000+" },
      { label: "VIP Clients", value: "200+" },
      { label: "Projects", value: "3,000+" },
    ],
    features: [
      "Technical SEO audit and crawlability fixes",
      "Arabic and English keyword strategy for Saudi market",
      "On-page optimization across all service pages",
      "Schema markup implementation for local search",
      "Google Business Profile optimization for Riyadh",
      "Content strategy aligned with service offerings",
      "Monthly ranking and traffic reports",
      "Competitor monitoring in Saudi advertising space",
    ],
    testimonial: {
      quote: "VELIQ's SEO work has brought us visibility we never had online. After 25 years of word-of-mouth, we're now being found by new clients through search.",
      author: "Window Advertising Team",
      role: "Window Advertising, Riyadh",
    },
    gallery: [],
  },
  {
    slug: "bedouin-trails",
    hidden: true,
    image: "/uploads/bedouin-trails-proj.png",
    tag: "Search Engine Optimization",
    title: "Bedouin Trails",
    desc: "SEO optimization for a Saudi desert tourism company, driving organic traffic for safari and adventure experiences.",
    fullDesc: "Bedouin Trails offers authentic desert safari and adventure tourism experiences across Saudi Arabia. We implemented an SEO strategy focused on tourism-related keywords to attract international and domestic travelers searching for Saudi desert experiences. The optimization covers technical SEO, content strategy, and local SEO to position Bedouin Trails as the top result for desert tourism in the Kingdom.",
    client: "Bedouin Trails",
    industry: "Tourism & Travel",
    timeline: "Ongoing",
    url: "https://bedouintrails.com",
    services: ["Search Engine Optimization", "Technical SEO", "Local SEO"],
    technologies: ["Google Search Console", "Google Analytics", "Semrush", "Schema.org"],
    challenge: "Bedouin Trails needed to compete for highly competitive tourism keywords in both English and Arabic markets. Desert safari tourism in Saudi Arabia is growing rapidly with Vision 2030, and they needed to capture this demand through organic search.",
    solution: "We built a tourism-focused SEO strategy targeting high-intent keywords like 'Saudi desert safari,' 'desert adventure Saudi Arabia,' and Arabic equivalents. Schema.org tourism markup was implemented for rich snippets. Local SEO optimization with Google Maps integration drives foot traffic. Content strategy focuses on travel guides and experience descriptions that rank for informational queries.",
    results: [
      { label: "Tour Types", value: "3" },
      { label: "Price Range", value: "$$" },
      { label: "Target Market", value: "Global" },
      { label: "Focus Area", value: "Saudi Desert" },
    ],
    features: [
      "Tourism-focused keyword strategy for Saudi desert experiences",
      "Schema.org tourism markup for rich search snippets",
      "Google Maps and local SEO optimization",
      "Multilingual content strategy (English and Arabic)",
      "Travel guide content creation for informational queries",
      "Social media integration with Facebook and Instagram",
      "WhatsApp booking integration for direct conversions",
      "Monthly organic traffic and ranking reports",
    ],
    testimonial: {
      quote: "Since VELIQ started our SEO, we're getting bookings from tourists who find us directly on Google. The organic traffic growth has been remarkable.",
      author: "Bedouin Trails Team",
      role: "Bedouin Trails, Saudi Arabia",
    },
    gallery: [],
  },
];

async function seed() {
  const url = process.env.DATABASE_URL || process.env.POSTGRES_URL;
  if (!url) {
    console.error("DATABASE_URL or POSTGRES_URL not set in .env.local");
    process.exit(1);
  }

  const sql = neon(url);

  await sql`
    CREATE TABLE IF NOT EXISTS collections (
      name TEXT PRIMARY KEY,
      data JSONB NOT NULL DEFAULT '[]'::jsonb,
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  await sql`
    INSERT INTO collections (name, data, updated_at)
    VALUES ('projects', ${JSON.stringify(projects)}::jsonb, NOW())
    ON CONFLICT (name)
    DO UPDATE SET data = ${JSON.stringify(projects)}::jsonb, updated_at = NOW()
  `;

  console.log(`Seeded ${projects.length} projects: ${projects.map(p => p.title).join(", ")}`);
}

seed().catch(console.error);
